# Generated by Django 5.2 on 2025-04-03 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('descripcion', models.TextField(blank=True)),
                ('disponible', models.BooleanField(default=True)),
            ],
            options={
                'permissions': [('can_manage_menu', 'Puede gestionar el menú')],
            },
        ),
    ]
