# Generated by Django 5.2 on 2025-04-04 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platillo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='platillos/'),
        ),
    ]
