# Generated by Django 5.2 on 2025-04-03 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='comida',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='ingredientes',
            new_name='items',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
