# Generated by Django 5.2 on 2025-04-04 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen_orders', '0002_delete_kitchenorder'),
        ('orders', '0002_rename_comida_menuitem_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
